### ISSUE TITLE
When g:buffergator_autoupdate=1, press any list in [Quickfix List] will open the list in buffergator's window

### ISSUE THREAD

**Issue by azltx** [jeetsukumaran/vim-buffergator#45]
I think when g:buffergator_autoupdate=1, and if the window has changed, it will go to buffergator's window to do the update and go back to the user's window.

Maybe due to that, the 'last window' will become the buffergator's window. So when I press 'enter' in the list. It is the buffergator's window being updated.

The issue will not be present if g:buffergator_autoupdate=0.

**Comment by ayevee** [comment]
I confirm the issue with buffergator constantly being the 'last window' with g:buffergator_autoupdate=1.

Have it reproducing with TagBar plugin - when I try to jump to tag definition the cursor jumps to buffergator window instead.

I get the same behaviour if I have several splits open - '<C-W>p' always brings me to buffergator window.

The issue is indeed not present with g:buffergator_autoupdate=0.
